workflows:
  android-workflow:
    name: Sanad Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Force Install Dependencies
        script: |
          rm -f .npmrc yarn.lock package-lock.json
          npm install -g pnpm --force
          pnpm install --no-frozen-lockfile --ignore-scripts
      - name: Build Android APK
        script: | 
          # هذا السطر سيبحث عن مجلد android ويخبرنا بمكانه
          ANDROID_PATH=$(find . -name "gradlew" -type f -not -path "*/node_modules/*" | sed 's/\/gradlew//')
          
          if [ -z "$ANDROID_PATH" ]; then
            echo "خطأ: لم نجد مجلد الأندرويد، سأعرض لك الملفات المتاحة الآن:"
            ls -R
            exit 1
          fi
          
          echo "تم العثور على المجلد في: $ANDROID_PATH"
          cd $ANDROID_PATH
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/app/outputs/apk/**/*.apk"
