import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import servicesRouter from "./services";
import ordersRouter from "./orders";
import suppliersRouter from "./suppliers";
import articlesRouter from "./articles";
import delegationsRouter from "./delegations";
import deliveryStaffRouter from "./deliveryStaff";
import promoBannersRouter from "./promoBanners";
import ratingsRouter from "./ratings";
import hotelBookingsRouter from "./hotelBookings";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import adsRouter from "./ads";
import deliveryConfigRouter from "./deliveryConfig";
import taxiRouter from "./taxi";
import tickerRouter from "./ticker";
import uploadRouter from "./upload";
import appSettingsRouter from "./appSettings";
import carRentalRouter from "./carRental";
import sosRouter from "./sos";
import lawyerRequestsRouter from "./lawyerRequests";
import pushRouter from "./push";
import partnersRouter from "./partners";
import searchRouter from "./search";
import messagesRouter from "./messages";
import resetRouter from "./reset";
import d17RenewalRouter from "./d17Renewal";
import promotionsRouter from "./promotions";
import generateApkRouter from "./generateApk";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(servicesRouter);
router.use(ordersRouter);
router.use(suppliersRouter);
router.use(articlesRouter);
router.use(delegationsRouter);
router.use(deliveryStaffRouter);
router.use(promoBannersRouter);
router.use(ratingsRouter);
router.use(hotelBookingsRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(adsRouter);
router.use(deliveryConfigRouter);
router.use(taxiRouter);
router.use(tickerRouter);
router.use(uploadRouter);
router.use(appSettingsRouter);
router.use(carRentalRouter);
router.use(sosRouter);
router.use(lawyerRequestsRouter);
router.use(pushRouter);
router.use(partnersRouter);
router.use(searchRouter);
router.use(messagesRouter);
router.use(resetRouter);
router.use(d17RenewalRouter);
router.use(promotionsRouter);
router.use("/generate-apk", generateApkRouter);

export default router;
